### ISSUE TITLE
请问如何打包？

### ISSUE THREAD

**Issue by lichangwei** [YaoKaiLun/react-image-editor#1]
我打算用在我的项目里，但是发现了如下问题：
1. 不支持多语言
2. 不支持修改固有插件的配置，比如输入文本默认采用更大的字体等。
3. 项目中图标字体 className 容易和其他项目（比如我们自己的组件库）冲突。

因此需要 fork 修改打包后使用，但是使用`npm run build`命令发现并没有打包出想要的lib目录出来？请求帮助。

**Comment by YaoKaiLun** [comment]
用的是 antd 的构建工具，https://github.com/react-component/rc-tools
我是直接构建发到 npm 包的，你可以试下 npm run pub，publish 的时候回报错，但应该可以构建出 lib 目录

**Comment by YaoKaiLun** [comment]
> 我打算用在我的项目里，但是发现了如下问题：
> 
> 1. 不支持多语言
> 2. 不支持修改固有插件的配置，比如输入文本默认采用更大的字体等。
> 3. 项目中图标字体 className 容易和其他项目（比如我们自己的组件库）冲突。
> 
> 因此需要 fork 修改打包后使用，但是使用`npm run build`命令发现并没有打包出想要的lib目录出来？请求帮助。

用的是 antd 的构建工具，https://github.com/react-component/rc-tools
我是直接构建发到 npm 包的，你可以试下 npm run pub，publish 的时候会报错，但应该可以构建出 lib 目录

**Comment by lichangwei** [comment]
收到，感谢
