### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by nzhingg** [YaoKaiLun/react-image-editor#10]
添加了crossOrigin属性，但还是一直报跨域的错误

**Comment by YaoKaiLun** [comment]
@nzhingg 是最新的版本吗，提供一个 codesandbox demo 地址

**Comment by nzhingg** [comment]
> 

找到问题了，是图片没有设置Access-Control-Allow-Origin导致的跨域所以展示不了，这个是canvas的限制问题
