### ISSUE TITLE
添加自定义组件后，组件并不在toolbar中显示

### ISSUE THREAD

**Issue by zhaosonggo** [YaoKaiLun/react-image-editor#12]

**Comment by YaoKaiLun** [comment]
@zhaosonggo 贴下具体的代码呢

**Comment by zhaosonggo** [comment]
我先阐述一下我的需求，我想增加一个填充矩形块的工具，所以自然的copy了项目中本身的rect代码，并修改了其中的绘制逻辑为fill

**Comment by zhaosonggo** [comment]
这是我的 rectFill.tsx
`import Konva from 'konva'
import Plugin from 'react-img-editor/lib/plugins/Plugin'
import { DrawEventParams, PluginParamName, PluginParamValue } from 'react-img-editor/lib/common/type'
import { transformerStyle } from 'react-img-editor/lib/common/constants'
import { uuid } from 'react-img-editor/lib/common/utils'

export default class RectFill extends Plugin {
  name = 'rectFill'
  iconfont = 'iconfont icon-triangle'
  title = '插入矩形'
  params = ['strokeWidth', 'lineType', 'color'] as PluginParamName[]
  defaultParamValue = {
    strokeWidth: 2,
    lineType: 'solid',
    color: '#F5222D',
  } as PluginParamValue
  shapeName = 'rectFill'

  lastRect: any = null
  transformer: any = null
  selectedNode: any = null
  isPaint = false // 防止切换插件时，onDraw 没有释放
  started = false // start draw 的标志
  startPoint = [0, 0]

  enableTransform = (drawEventParams: DrawEventParams, node: any) => {
    const {stage, drawLayer} = drawEventParams

    if (!this.transformer) {
      this.transformer = new Konva.Transformer({ ...transformerStyle, borderStrokeWidth: 0 })
      drawLayer.add(this.transformer)
      this.transformer.attachTo(node)
      node.on('mouseenter', function() {
        stage.container().style.cursor = 'move'
      })
      node.on('mouseleave', function() {
        stage.container().style.cursor = 'default'
      })
      stage.container().style.cursor = 'move'
    }

    node && node.draggable(true)
    drawLayer.draw()
  }

  disableTransform = (drawEventParams: DrawEventParams, node: any, remove?: boolean) => {
    const {stage, drawLayer, pubSub} = drawEventParams

    if (this.transformer) {
      this.transformer.remove()
      this.transformer = null
    }

    if (node) {
      node.draggable(false)
      node.off('mouseenter')
      node.off('mouseleave')
      stage.container().style.cursor = 'default'

      if (remove) {
        node.hide()
        // 使用隐藏节点占位并覆盖堆栈中已有节点
        pubSub.pub('PUSH_HISTORY', node)
        node.remove()
      }
    }

    this.selectedNode = null
    drawLayer.draw()
  }

  onEnter = (drawEventParams: DrawEventParams) => {
    const {stage, drawLayer} = drawEventParams
    const container = stage.container()
    container.tabIndex = 1 // make it focusable
    container.focus()
    container.addEventListener('keyup', (e: any) => {
      if (e.key === 'Backspace' && this.selectedNode) {
        this.disableTransform(drawEventParams, this.selectedNode, true)
        drawLayer.draw()
      }
    })
  }

  onClick = (drawEventParams: DrawEventParams) => {
    const {event} = drawEventParams

    if (event.target.name && event.target.name() === 'rectFill') {
      // 之前没有选中节点或者在相同节点之间切换点击
      if (!this.selectedNode || this.selectedNode._id !== event.target._id) {
        this.selectedNode && this.disableTransform(drawEventParams, this.selectedNode)
        this.enableTransform(drawEventParams, event.target)
        this.selectedNode = event.target
      }
    } else {
      this.disableTransform(drawEventParams, this.selectedNode)
    }
  }

  onDrawStart = () => {
    this.isPaint = true
  }

  onDraw = (drawEventParams: DrawEventParams) => {
    const {stage, drawLayer, paramValue, pubSub} = drawEventParams
    const pos = stage.getPointerPosition()

    if (!this.isPaint || this.transformer || !pos) return

    if (!this.started) {
      this.startPoint = [pos.x, pos.y]
      this.lastRect = new Konva.Rect({
        id: uuid(),
        name: 'rect',
        fill: (paramValue && paramValue.color) ? paramValue.color : this.defaultParamValue.color,
        globalCompositeOperation: 'source-over',
        x: pos.x,
        y: pos.y,
        dashEnabled: !!(paramValue && paramValue.lineType && paramValue.lineType === 'dash'),
        dash: [8],
        strokeScaleEnabled: false,
      })
      this.lastRect.on('transformend', function() {
        pubSub.pub('PUSH_HISTORY', this)
      })
      this.lastRect.on('dragend', function() {
        pubSub.pub('PUSH_HISTORY', this)
      })
      drawLayer.add(this.lastRect)
      this.started = true
    }

    this.lastRect.width(pos.x - this.startPoint[0])
    this.lastRect.height(pos.y - this.startPoint[1])
    drawLayer.batchDraw()
  }

  onDrawEnd = (drawEventParams: DrawEventParams) => {
    const {pubSub} = drawEventParams

    // mouseup event is triggered by move event but click event
    if (this.started) {
      this.disableTransform(drawEventParams, this.selectedNode)
      if (this.lastRect) {
        pubSub.pub('PUSH_HISTORY', this.lastRect)
      }
    }
    this.isPaint = false
    this.started = false
  }

  onLeave = (drawEventParams: DrawEventParams) => {
    this.isPaint = false
    this.started = false
    this.disableTransform(drawEventParams, this.selectedNode)
  }

  onNodeRecreate = (drawEventParams: DrawEventParams, node: any) => {
    const {pubSub} = drawEventParams
    node.on('transformend', function() {
      pubSub.pub('PUSH_HISTORY', this)
    })
    node.on('dragend', function() {
      pubSub.pub('PUSH_HISTORY', this)
    })
  }
}`

**Comment by zhaosonggo** [comment]
这是我的使用方式
`<ReactImageEditor
                                        src={xxx}
                                        width={700}
                                        height={800}
                                        plugins={[new RectFill()]}
                                        getStage={setStage}
                                        defaultPluginName="rectFill"
                                        crossOrigin="Anonymous"
                                    />`

**Comment by zhaosonggo** [comment]
最奇怪的是 ，我查看dome是没有 这个新增的rectFill 工具，但是通过 defaultPluginName设置为默认工具时，可以生效

**Comment by zhaosonggo** [comment]
<img width="763" alt="截屏2023-01-28 下午10 09 03" src="https://user-images.githubusercontent.com/44077994/215270944-0c33df59-a79c-4e29-9cb7-f5a793b23afe.png">

可以看到，确实通过defaultPluginName 设置成功了

**Comment by zhaosonggo** [comment]
但是 dom中 只有默认的十个
<img width="1531" alt="截屏2023-01-28 下午10 08 55" src="https://user-images.githubusercontent.com/44077994/215271131-70a23d53-351f-45e9-ba93-996b53549e4c.png">

**Comment by YaoKaiLun** [comment]
你需要设置这个属性
<img width="866" alt="image" src="https://user-images.githubusercontent.com/11460856/215272554-f46f2afa-2240-4769-bd41-5052bbc055e9.png">

**Comment by YaoKaiLun** [comment]
@zhaosonggo 是否可行？

**Comment by zhaosonggo** [comment]
可以的，我这边试了下，感谢老哥

**Comment by mifengdeyanjing** [comment]
我想问你知道怎么写放大缩小的自定义插件吗

**Comment by mifengdeyanjing** [comment]
> 可以的，我这边试了下，谢谢老哥

我想问你知道怎么写放大缩小的自定义插件吗
