### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by aaxuyun** [YaoKaiLun/react-image-editor#3]
img元素中设置了crossorigin属性，图片无法显示，这个属性设置能不能给外部开放

**Comment by YaoKaiLun** [comment]
@aaxuyun 可以，晚点加上，确定是这个导致的吗

**Comment by aaxuyun** [comment]
确定是的，之前用这个试验过，加上这个地址图片无法显示，不加的话imageLayer的canvas又无法导出, 不过我们现在的需求只需要导出绘制层，不用将绘制层和图片叠加导出 。另外想问一下，如果想自定义插件进行图片放大缩小的操作，这个可以实现吗？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kailunyao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 下午3:33
收件人:&nbsp;"YaoKaiLun/react-img-editor"<react-img-editor@noreply.github.com&gt;;
抄送:&nbsp;"雨落月华升"<784266498@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [YaoKaiLun/react-img-editor] 图片无法显示 (#3)





 
@aaxuyun 可以，晚点加上，确定是这个导致的吗

**Comment by aaxuyun** [comment]
确定是的，之前用这个试验过，加上这个图片无法显示，不加的话imageLayer的canvas又无法导出, 不过我们现在的需求只需要导出绘制层，不用将绘制层和图片叠加导出 。另外想问一下，如果想自定义插件进行图片放大缩小的操作，这个可以实现吗？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kailunyao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 下午3:33
收件人:&nbsp;"YaoKaiLun/react-img-editor"<react-img-editor@noreply.github.com&gt;;
抄送:&nbsp;"雨落月华升"<784266498@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [YaoKaiLun/react-img-editor] 图片无法显示 (#3)





 
@aaxuyun 可以，晚点加上，确定是这个导致的吗

**Comment by YaoKaiLun** [comment]
@aaxuyun 图片放大缩小目前我还没想过，不太好实现，因为会影响到裁剪和马赛克的功能
