### ISSUE TITLE
请问如何导出修改后的图片

### ISSUE THREAD

**Issue by Bibabo-BUPT** [YaoKaiLun/react-image-editor#6]
现在的组件有一个下载按钮，但是我希望实现编辑完成之后点击一个按钮能够把修改后的图片自动上传到oss中，请问应该如何实现呢？

**Comment by YaoKaiLun** [comment]
@Bibabo-BUPT 你可以参考这个写一个自己的插件 https://github.com/YaoKaiLun/react-img-editor/blob/master/src/plugins/Download.ts

**Comment by Bibabo-BUPT** [comment]
> @Bibabo-BUPT 你可以参考这个写一个自己的插件 https://github.com/YaoKaiLun/react-img-editor/blob/master/src/plugins/Download.ts

好滴，我去看看，谢谢嗷~
